version: "3.9"

# 실서버에서 사용하는 환경

services:
  main:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: colorful_web
    volumes:
      - ./:/home
    ports:
      - "9080:8000"